### ISSUE TITLE
Dilvish's FreeOrion 0.4.5 Release ToDo list

### ISSUE THREAD

**Issue by Dilvish-fo** [Dilvish-fo/freeorion#8]
To help organize my TODO list, and to make it easy for other people to see what I have on my list and nudge me if they think I'm overlooking something, I'm making that list here.
- [x] freeorion/freeorion#253
  - [x] initial responsive PR freeorion/freeorion#258 submitted
  - [x] PR finalized & cherrypicked to 0.4.5
- [x] fix GGG custom sitrep triggering extra times for buildings on the GG
  - [x] fix submitted as part of PR 258
  - [x] finalized and cherrypicked
- [x] freeorion/freeorion#254
  - [x] fix submitted as part of PR freeorion/freeorion#260
  - [x] finalized and cherrypicked
